   return {
      color_window_background = "#16141f",
      color_cursor_foreground = "#16141f",
      color_background        = "#16141f",
      color_0                 = "#16141f",
      color_foreground        = "#e0def4",
      color_7                 = "#908caa",
      color_bold              = "#e0def4",
      color_8                 = "#524f67",
      color_15                = "#e0def4",
      color_cursor            = "#e0def4",
      color_9                 = "#eb6f92",
      color_1                 = "#eb6f92",
      color_10                = "#31748f",
      color_2                 = "#31748f",
      color_11                = "#f6c177",
      color_3                 = "#f6c177",
      color_12                = "#9ccfd8",
      color_4                 = "#9ccfd8",
      color_13                = "#c4a7e7",
      color_5                 = "#c4a7e7",
      color_14                = "#ebbcba",
      color_6                 = "#ebbcba"
   }
